### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/clubs
Content-Type: application/json

{
  "clubName": "Sporting",
  "city": "Lisboa",
  "yearFounded": 1906
}

###
GET http://localhost:8080/api/clubs

###
DELETE http://localhost:8080/api/clubs/3

###
GET http://localhost:8080/api/clubs/3

###
PUT http://localhost:8080/api/clubs/3
Content-Type: application/json

{
  "clubName": "SC Braga",
  "city": "Braga",
  "yearFounded": 1950
}
###

GET http://localhost:8080/api/players

###
POST http://localhost:8080/api/clubs/2/players
Content-Type: application/json

{
  "name": "Diogo Costa",
  "age": 24,
  "position": "GK",
  "shirtNumber": 1
}

###
GET http://localhost:8080/api/clubs/1/players
###

GET http://localhost:8080/api/players/2

###
PUT http://localhost:8080/api/players/2
Content-Type: application/json

{
  "name": "Pavlidis",
  "age": 26,
  "position": "ST",
  "shirtNumber": 9
}